import { useState } from "react";

import Modal from "react-modal";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import useTrader from "../components/useTrader";

export default function Home() {
  const [amount, setAmount] = useState();
  const [modalIsOpen, setModalIsOpen] = useState(false);
  const { assets } = useTrader();

  const closeModal = () => {
    setModalIsOpen(false);
  };

  const afterOpenModal = () => {};

  const customStyles = {
    overlay: {
      position: "fixed",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(33, 36, 41, 0.75)",
    },
    content: {
      top: "30%",
      left: "50%",
      right: "auto",
      bottom: "auto",
      marginRight: "-50%",
      transform: "translate(-50%, -50%)",
      backgroundColor: "rgb(33, 36, 41)",
      border: "1px solid rgb(44, 47, 54)",
      borderRadius: "20px",
      width: "100%",
      maxWidth: "480px",
      padding: 0,
      color: "white",
    },
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.trader}>
          <div className={styles.heading}>Buy</div>
          <div className={styles.selector}>
            <div className={styles.assetWrapper}>
              <button
                className={styles.asset}
                onClick={() => setModalIsOpen(true)}
              >
                <span className={styles.assetText}>ETH</span>
                <span className={styles.caret}>
                  <svg
                    width="12"
                    height="7"
                    viewBox="0 0 12 7"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    className="sc-33m4yg-8 kcdsjA"
                  >
                    <path d="M0.97168 1L6.20532 6L11.439 1" stroke="#AEAEAE" />
                  </svg>
                </span>
              </button>
              <Modal
                isOpen={modalIsOpen}
                onAfterOpen={afterOpenModal}
                onRequestClose={closeModal}
                style={customStyles}
                contentLabel="Buy"
              >
                <div className={styles.modalBody}>
                  <div className={styles.modalHeader}>
                    <h3>Select asset</h3>
                    <button className={styles.close} onClick={closeModal}>
                      X
                    </button>
                  </div>
                  {/*<input*/}
                  {/*  ref={inputEl}*/}
                  {/*  className={styles.assetSelector}*/}
                  {/*  placeholder="Search name"*/}
                  {/*/>*/}
                </div>
                <div className={styles.assetList}>
                  {assets.map((o) => (
                    <div className={styles.assetClass}>
                      <img src={o.imageURL} />
                      <div className={styles.assetName}>
                        <div>{o.short}</div>
                        <div>{o.name}</div>
                      </div>
                      <div>${o.price}</div>
                    </div>
                  ))}
                </div>
              </Modal>
              <input
                className={styles.amount}
                onChange={(e) => setAmount(e.target.value)}
                value={amount}
                placeholder="0"
              />
            </div>
            <button className={styles.buy}>Buy</button>
          </div>
        </div>
      </main>
    </div>
  );
}
